import "./globals.css";

export const metadata = {
  title: "Next-App-Router",
  description: "Generated by Next-App-Router",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>This is Header page</p>
        </header>
        {children}

        <footer>This is Footer Page</footer>
      </body>
    </html>
  );
}
